### ISSUE TITLE
non-strict mode

### ISSUE THREAD

**Issue by bfontaine** [sagotch/pastek-lang#6]
Some markdown parsers allow errors in syntax and still process the input, e.g:

```
$ maruku <<< "aa**" 2>/dev/null

<p>aa**</p>
$ kramdown <<< "aa**"
<p>aa**</p>
```

Also note that Maruku gives human-friendly errors, e.g.:

```
$ maruku <<< "aa**"

 ___________________________________________________________________________
| Maruku tells you:
+---------------------------------------------------------------------------
| Opening * as last char.
| ---------------------------------------------------------------------------
| aa**EOF
| ---|------------------------------------------------------------------------
|    +--- Byte 3
| Shown bytes [0 to 4] of 4:
| >aa**
|
| At line 2
|       text     |aa**|
|
|
| Elements read in span:
|  -
| Current string:
|   "aa*"
|
|
| Recovering: Treating as literal
+---------------------------------------------------------------------------
!/Users/baptiste/.rvm/gems/ruby-2.0.0-p247/gems/maruku-0.7.1/lib/maruku/input/parse_span.rb:142:in `read_span'
!/Users/baptiste/.rvm/gems/ruby-2.0.0-p247/gems/maruku-0.7.1/lib/maruku/input/parse_span.rb:14:in `parse_span'
!/Users/baptiste/.rvm/gems/ruby-2.0.0-p247/gems/maruku-0.7.1/lib/maruku/input/parse_block.rb:287:in `read_paragraph'
!/Users/baptiste/.rvm/gems/ruby-2.0.0-p247/gems/maruku-0.7.1/lib/maruku/input/parse_block.rb:154:in `read_text_material'
\___________________________________________________________________________


<p>aa**</p>
$ pastek <<< "aa**"
Fatal error: exception Parser.Error
```

By default, Maruku will process the input even if there’s an error, but it can be told to break on error: `maruku --break`.

**Comment by sagotch** [comment]
Latest version gives line and column numbers of syntax error.

I will think about how to add the `--non-strict` mode.

**Comment by bfontaine** [comment]
up?

**Comment by bfontaine** [comment]
I guess this is dead :stuck_out_tongue:

**Comment by sagotch** [comment]
I think this _new_ markup language is pointless...

**Comment by bfontaine** [comment]
I’m cleaning up my old issues.

**Comment by sagotch** [comment]
I do not care. This issue is not fixed dude.

**Comment by bfontaine** [comment]
![](https://media.giphy.com/media/dWhHUkuWnGxFK/giphy.gif)
